name: Mock NGC Push and Update

on:
  workflow_dispatch:
    inputs:
      new_tag:
        description: 'New tag for the image'
        required: true

jobs:
  mock-ngc-push:
    runs-on: ubuntu-latest
    container:
      image: quay.io/liveaverage/ci-builder:latest
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Mock NGC Push
        run: |
          echo "Mocking push to NGC with tag: ${{ github.event.inputs.new_tag }}"
          echo "nvcr.io/your_org/your_image:${{ github.event.inputs.new_tag }}" > latest_image.txt

      - name: Update launch-list.yml with new image tag 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python update_launch_list.py ${{ github.event.inputs.new_tag }}

      - name: Upload updated launch-list.yml
        uses: actions/upload-artifact@v3
        with:
          name: updated-launch-list
          path: launch-list.yml

  commit-and-push:
    needs: mock-ngc-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download updated launch-list.yml
        uses: actions/download-artifact@v3
        with:
          name: updated-launch-list

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add launch-list.yml
          git diff --quiet && git diff --staged --quiet || (git commit -m "tag: updated image tag to ${{ github.event.inputs.new_tag }}" && git push)